name: habit_hive
description: A habit tracking app built with Flutter and Firebase.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0

  # Firebase packages compatible with Flutter 3.35.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # For launching email or external URLs
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/bee_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bee_logo.png"
  adaptive_icon_background: "#ffffff"  # white background
  adaptive_icon_foreground: "assets/images/bee_logo.png"
